#Game Constants for events

GAME_INIT=0
GAME_SHUTDOWN=1
GAME_CLIENT_CONNECT=2
GAME_CLIENT_BEGIN=3
GAME_CLIENT_USERINFO_CHANGED=4
GAME_CLIENT_DISCONNECT=5
GAME_CLIENT_COMMAND=6
GAME_CLIENT_THINK=7
GAME_RUN_FRAME=8
GAME_CONSOLE_COMMAND=9
BOTAI_START_FRAME=10
