#Game Constants for events
GAME_INIT=0
GAME_SHUTDOWN=1
GAME_CLIENT_CONNECT=2
GAME_CLIENT_BEGIN=3
GAME_CLIENT_USERINFO_CHANGED=4
GAME_CLIENT_DISCONNECT=5
GAME_CLIENT_COMMAND=6
GAME_CLIENT_THINK=7
GAME_RUN_FRAME=8
GAME_CONSOLE_COMMAND=9
BOTAI_START_FRAME=10
##

#misc
MAX_CLIENTS = 64
MAX_MODELS = 256 
MAX_SOUNDS = 256 
MAX_CS_SKINS = 64
MAX_CSSTRINGS = 32
MAX_CS_SHADERS = 32
MAX_SERVER_TAGS = 256
MAX_TAG_FILES = 64
MAX_MULTI_SPAWNTARGETS = 16
MAX_DLIGHT_CONFIGSTRINGS = 16
MAX_SPLINE_CONFIGSTRINGS = 8
MAX_OID_TRIGGERS = 18
MAX_CHARACTERS = 16
MAX_TAGCONNECTS = 64
MAX_FIRETEAMS = 12
MAX_MOTDLINES = 6
#


#ConfigString index
CS_SERVERINFO = 0
CS_SYSTEMINFO = 1
CS_MUSIC = 2
CS_MESSAGE = 3
CS_MOTD = 4
CS_WARMUP = 5
CS_VOTE_TIME = 6
CS_VOTE_STRING = 7
CS_VOTE_YES = 8
CS_VOTE_NO = 9
CS_GAME_VERSION = 10
CS_LEVEL_START_TIME = 11
CS_INTERMISSION = 12
CS_MULTI_INFO = 13
CS_MULTI_MAPWINNER = 14
CS_MULTI_OBJECTIVE = 15
CS_SCREENFADE = 17
CS_FOGVARS = 18
CS_SKYBOXORG = 19
CS_TARGETEFFECT = 20
CS_WOLFINFO = 21
CS_FIRSTBLOOD = 22
CS_ROUNDSCORES1 = 23
CS_ROUNDSCORES2 = 24
CS_MAIN_AXIS_OBJECTIVE = 25
CS_MAIN_ALLIES_OBJECTIVE = 26
CS_MUSIC_QUEUE = 27
CS_SCRIPT_MOVER_NAMES = 28
CS_CONSTRUCTION_NAMES = 29
CS_VERSIONINFO = 30
CS_REINFSEEDS =  31 
CS_SERVERTOGGLES =  32
CS_GLOBALFOGVARS = 33
CS_AXIS_MAPS_XP =  34
CS_ALLIED_MAPS_XP = 35
CS_INTERMISSION_START_TIME = 36
CS_ENDGAME_STATS = 37
CS_CHARGETIMES = 38
CS_FILTERCAMS =  39
CS_MODELS =      64
CS_SOUNDS = CS_MODELS + MAX_MODELS
CS_SHADERS =     CS_SOUNDS + MAX_SOUNDS     
CS_SHADERSTATE =      CS_SHADERS + MAX_CS_SHADERS  
CS_SKINS =       CS_SHADERSTATE +   1       
CS_CHARACTERS =      CS_SKINS + MAX_CS_SKINS    
CS_PLAYERS =       CS_CHARACTERS + MAX_CHARACTERS    
CS_MULTI_SPAWNTARGS =   CS_PLAYERS + MAX_CLIENTS     
CS_OID_TRIGGERS =      CS_MULTI_SPAWNTARGS + MAX_MULTI_SPAWNTARGETS  
CS_OID_DATA =       CS_OID_TRIGGERS + MAX_OID_TRIGGERS   
CS_DLIGHTS =       CS_OID_DATA + MAX_OID_TRIGGERS   
CS_SPLINES =       CS_DLIGHTS + MAX_DLIGHT_CONFIGSTRINGS 
CS_TAGCONNECTS =      CS_SPLINES + MAX_SPLINE_CONFIGSTRINGS 
CS_FIREAMS =      CS_TAGCONNECTS + MAX_TAGCONNECTS    
CS_CUSTMOTD =       CS_FIREAMS + MAX_FIRETEAMS    
CS_STRINGS =       CS_CUSTMOTD + MAX_MOTDLINES    
CS_MAX =        CS_STRINGS + MAX_CSSTRINGS    


#pyet utils 

pyet_events = ("GameInit", "GameShutdown", "ClientConnect", 
               "ClientBegin", "ClientUserInfoChanged", "ClientDisconnect",
               "ClientCommand", "ClientThink", "GameRunFrame",
               "GameConsoleCommand")

