#include <stddef.h>

#include "pyet.h"
#include "fields.h"

#define GENT_FIELD(name, type, flags) \
	{#name, offsetof(gentity_t, name), type, flags}

#define GCLI_FIELD(name, type, flags) \
	{#name, offsetof(gclient_t, name), type, flags}

static const struct gentity_field gentity_fields[] = {

GENT_FIELD(client, FIELD_CLIENT, FIELD_FLAG_READONLY),
GENT_FIELD(activator, FIELD_ENTITY, FIELD_FLAG_READONLY),
GENT_FIELD(chain, FIELD_ENTITY, FIELD_FLAG_NONE),
GENT_FIELD(classname, FIELD_STRING, FIELD_FLAG_NONE),
GENT_FIELD(clipmask, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(closespeed, FIELD_FLOAT, FIELD_FLAG_NONE),
GENT_FIELD(count, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(count2, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(damage, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(deathType, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(delay, FIELD_FLOAT, FIELD_FLAG_NONE),
GENT_FIELD(dl_atten, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(dl_shader, FIELD_STRING, FIELD_FLAG_READONLY),
GENT_FIELD(dl_stylestring, FIELD_STRING, FIELD_FLAG_READONLY),
GENT_FIELD(duration, FIELD_FLOAT, FIELD_FLAG_NONE),
GENT_FIELD(end_size, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(enemy, FIELD_ENTITY, FIELD_FLAG_NONE),
GENT_FIELD(entstate, FIELD_INT, FIELD_FLAG_READONLY),
GENT_FIELD(flags, FIELD_INT, FIELD_FLAG_READONLY),
GENT_FIELD(harc, FIELD_FLOAT, FIELD_FLAG_NONE),
GENT_FIELD(health, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(inuse, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(isProp, FIELD_INT, FIELD_FLAG_READONLY),
GENT_FIELD(item, FIELD_STRING, FIELD_FLAG_READONLY),
GENT_FIELD(key, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(message, FIELD_STRING, FIELD_FLAG_NONE),
GENT_FIELD(methodOfDeath, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(mg42BaseEnt, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(missionLevel, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(model, FIELD_STRING, FIELD_FLAG_READONLY),
GENT_FIELD(model2, FIELD_STRING, FIELD_FLAG_READONLY),
GENT_FIELD(nextTrain, FIELD_ENTITY, FIELD_FLAG_NONE),
GENT_FIELD(noise_index, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(prevTrain, FIELD_ENTITY, FIELD_FLAG_NONE),
GENT_FIELD(props_frame_state, FIELD_INT, FIELD_FLAG_READONLY),
GENT_FIELD(scriptName, FIELD_STRING, FIELD_FLAG_READONLY),
GENT_FIELD(spawnflags, FIELD_INT, FIELD_FLAG_READONLY),
GENT_FIELD(spawnitem, FIELD_STRING, FIELD_FLAG_READONLY),
GENT_FIELD(speed, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(splashDamage, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(splashMethodOfDeath, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(splashRadius, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(start_size, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(tagName, FIELD_STRING, FIELD_FLAG_NOPTR),
GENT_FIELD(tagParent, FIELD_ENTITY, FIELD_FLAG_NONE),
GENT_FIELD(takedamage, FIELD_INT, FIELD_FLAG_NONE),
GENT_FIELD(tankLink, FIELD_ENTITY, FIELD_FLAG_NONE),
GENT_FIELD(target, FIELD_STRING, FIELD_FLAG_NONE),
GENT_FIELD(TargetFlag, FIELD_INT, FIELD_FLAG_READONLY),
GENT_FIELD(targetname, FIELD_STRING, FIELD_FLAG_READONLY),
GENT_FIELD(teamchain, FIELD_ENTITY, FIELD_FLAG_NONE),
GENT_FIELD(teammaster, FIELD_ENTITY, FIELD_FLAG_NONE),
GENT_FIELD(track, FIELD_STRING, FIELD_FLAG_READONLY),
GENT_FIELD(varc, FIELD_FLOAT, FIELD_FLAG_NONE),
GENT_FIELD(wait, FIELD_FLOAT, FIELD_FLAG_NONE),
GENT_FIELD(waterlevel, FIELD_INT, FIELD_FLAG_READONLY),
GENT_FIELD(watertype, FIELD_INT, FIELD_FLAG_READONLY),

};


static const struct gentity_field gclient_fields[] = {

GCLI_FIELD(noclip, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(lastKillTime, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(saved_persistant, FIELD_INT_ARRAY, FIELD_FLAG_READONLY),
GCLI_FIELD(lastConstructibleBlockingWarnTime, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(landmineSpottedTime, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(lasthurt_client, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(lasthurt_mod, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(respawnTime, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(inactivityTime, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(inactivityWarning, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(combatState, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(deathTime, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(medals, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(acc, FIELD_FLOAT, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.connected, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.netname, FIELD_STRING, FIELD_FLAG_NOPTR),
GCLI_FIELD(pers.localClient, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.initialSpawn, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.enterTime, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.connectTime, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.teamState.state, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.voteCount, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.complaints, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.complaintClient, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.complaintEndTime, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.lastReinforceTime, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.applicationClient, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.applicationEndTime, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.invitationClient, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.invitationEndTime, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.propositionClient, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.propositionClient2, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.propositionEndTime, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.autofireteamEndTime, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.autofireteamCreateEndTime, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.autofireteamJoinEndTime, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.lastSpawnTime, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.ready, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.playerStats.hitRegions, FIELD_INT_ARRAY, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.lastBattleSenseBonusTime, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.lastHQMineReportTime, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.maxHealth, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(ps.pm_flags, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(ps.pm_time, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(ps.pm_type, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(ps.eFlags, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(ps.weapon, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(ps.weaponstate, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(ps.stats, FIELD_INT_ARRAY, FIELD_FLAG_NONE),
GCLI_FIELD(ps.persistant, FIELD_INT_ARRAY, FIELD_FLAG_NONE),
GCLI_FIELD(ps.ping, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(ps.powerups, FIELD_INT_ARRAY, FIELD_FLAG_NONE),
GCLI_FIELD(ps.ammo, FIELD_INT_ARRAY, FIELD_FLAG_NONE),
GCLI_FIELD(ps.ammoclip, FIELD_INT_ARRAY, FIELD_FLAG_NONE),
GCLI_FIELD(ps.classWeaponTime, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(ps.viewheight, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(ps.leanf, FIELD_FLOAT, FIELD_FLAG_READONLY),
GCLI_FIELD(sess.sessionTeam, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.spectatorTime, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.spectatorState, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.spectatorClient, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.playerType, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.playerWeapon, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.playerWeapon2, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.latchPlayerType, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.latchPlayerWeapon, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.latchPlayerWeapon2, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.ignoreClients, FIELD_INT_ARRAY, FIELD_FLAG_NONE),
GCLI_FIELD(sess.muted, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.skillpoints, FIELD_FLOAT_ARRAY, FIELD_FLAG_READONLY),
GCLI_FIELD(sess.startskillpoints, FIELD_FLOAT_ARRAY, FIELD_FLAG_READONLY),
GCLI_FIELD(sess.startxptotal, FIELD_FLOAT, FIELD_FLAG_READONLY),
GCLI_FIELD(sess.skill, FIELD_INT_ARRAY, FIELD_FLAG_NONE),
GCLI_FIELD(sess.rank, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.medals, FIELD_INT_ARRAY, FIELD_FLAG_NONE),
GCLI_FIELD(sess.referee, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.rounds, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.spec_invite, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.spec_team, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.kills, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.deaths, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.team_kills, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.damage_given, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.damage_received, FIELD_INT, FIELD_FLAG_NONE),


#ifdef HEADERS_ETLEGACY

GCLI_FIELD(sess.userSpawnPointValue, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.shoutcaster, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.lastammo_client, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.lasthealth_client, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(pers.lastteambleed_client, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.lastteambleed_dmg, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.playerStats.selfkills, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(sess.self_kills, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.team_gibs, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.gibs, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.team_damage_given, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.team_damage_received, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(sess.time_axis, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(sess.time_allies, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(sess.time_played, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.lastkilled_client, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.lastrevive_client, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(pers.lastkiller_client, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(constructSoundTime, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(freezed, FIELD_INT, FIELD_FLAG_NONE),
GCLI_FIELD(hspct, FIELD_FLOAT, FIELD_FLAG_READONLY),
GCLI_FIELD(disguiseClientNum, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(deathAnimTime, FIELD_INT, FIELD_FLAG_READONLY),
GCLI_FIELD(lasthurt_time, FIELD_INT, FIELD_FLAG_READONLY),

#endif

/* ETlegacy last stuffs, not implementing this for now
 * GCLI_FIELD(sess.mu, FIELD_FLOAT, FIELD_FLAG_READONLY),
 * GCLI_FIELD(sess.sigma, FIELD_FLOAT, FIELD_FLAG_READONLY),
 * GCLI_FIELD(sess.oldmu, FIELD_FLOAT, FIELD_FLAG_READONLY),
 * GCLI_FIELD(sess.oldsigma, FIELD_FLOAT, FIELD_FLAG_READONLY),
 * GCLI_FIELD(sess.prestige, FIELD_INT, FIELD_FLAG_READONLY),
 * GCLI_FIELD(sess.uci, FIELD_INT, FIELD_FLAG_NONE),
 * GCLI_FIELD(sess.aWeaponStats, FIELD_WEAPONSTAT, FIELD_FLAG_READONLY),
 */

};


const struct gentity_field *gentity_get_fields(void)
{
	return gentity_fields;
}

size_t gentity_get_fields_count(void)
{
	return sizeof(gentity_fields) / sizeof(const struct gentity_field);
}

const struct gentity_field *gclient_get_fields(void)
{
	return gclient_fields;
}

size_t gclient_get_fields_count(void)
{

	return sizeof(gclient_fields) / sizeof(const struct gentity_field);
}
